### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by ephemeralsnow**

### CODE REVIEW

**Comment by toyama0919** [comment]
Ah Thanks :blush:

**Comment by toyama0919** [comment]
Please release rubygems :pray:

**Comment by ephemeralsnow** [comment]
It plans to v0.1.0. Please wait a moment.

Thank you for your contribution!

**Comment by toyama0919** [comment]
> It plans to v0.1.0. Please wait a moment.

Oh thanks :blush:

**Comment by ephemeralsnow** [comment]
released v0.1.0

**Pull request merged**
